### ISSUE TITLE
Use slashes instead of backslashes for file paths

### ISSUE THREAD

**Issue by LoganTann** [davestewart/nuxt-content-assets#37]
## Background

When running this extension in a Windows OS, relative urls generated by this extension include both slashes and backslashes.

![image](https://user-images.githubusercontent.com/28659185/234257625-9befed29-7b66-47a4-bc8e-022f9a738c30.png)

## Proposal

While it does not break anything (image are still correctly rendered), it may be safer to replace backslashes by slashes.

## Notes

None

**Comment by davestewart** [comment]
Thanks - good spot! I'll get on that.
