### ISSUE TITLE
How to reference images from outside markdown files?

### ISSUE THREAD

**Issue by jvolker** [davestewart/nuxt-content-assets#58]
I've previously described my issue here: https://github.com/davestewart/nuxt-content-assets/issues/45. The issue was closed, but I don't have a solution yet. Any help would be highly appreciated. Thank you.

**Comment by davestewart** [comment]
Hey, sorry to leave you hanging, right at the end of a sprint! 

If you can wait a few more days, I should be done by next week

**Comment by jvolker** [comment]
Thanks so much for getting back. No worries, of course, I can wait. I just wasn't sure if my last message got lost. Thanks for your help in advance.

**Comment by jvolker** [comment]
@davestewart let me know if there is anything I can do on my end. I don't mean to bother but really appreciate your help.

**Comment by davestewart** [comment]
Hey,

Commented on your other issue; I have been a bit [busy](https://youtu.be/jIxSjGihq5w).

i have a little time for OSS at the mo, but not much. I can't promise, but just letting you know I have read your issue 👀

**Comment by jvolker** [comment]
No worries. Thanks so much for your reply.

I have been able to solve my issues and posted my solution in https://github.com/davestewart/nuxt-content-assets/issues/45.

I am just leaving this open since the other issue is closed and I was not sure if you might want to use this issue to point out a more sophisticated solution to the problem. Feel free to close it, if there is not much to add to this.

**Comment by davestewart** [comment]
Closing this now as it looks like everything should now work from `v1.4.3` onwards.
