### ISSUE TITLE
Files with leading underscore `_` are not being picked up

### ISSUE THREAD

**Issue by jvolker** [davestewart/nuxt-content-assets#59]
## Description

Images/Files starting with and underscore character are not being picked up. If they are include the underscore they are not copied into `.nuxt/content-assets/`. In combination with Nuxt Image this leads to `IPX Error: Error: File not found`

## To reproduce:

Add underscore to start of a file name and check `.nuxt/content-assets/` Eg.: 
- "image.jpg" works
- "_image.jpg" fails

**Comment by davestewart** [comment]
Hey Jeremias,

Sorry for the radio-silence the last few weeks, I've been working every waking hour on the release of [Control Space](https://youtu.be/jIxSjGihq5w)! Anyway, it's done now so I have time to breath, and a little for OSS.

This is actually a Nuxt feature; any file with an underscore is deemed "hidden".

Can I find this in the Nuxt documentation for you now? Of course I can't! 😆

But this repo even has tests to ensure it adheres:

- https://github.com/davestewart/nuxt-content-assets/tree/main/demo/content/advanced/_hidden

**Comment by jvolker** [comment]
Thanks so much for your response. And no worries. Of course, I totally understand that you have limited time for this.

> I've been working every waking hour on the release of [Control Space](https://youtu.be/jIxSjGihq5w)!

Love your tool! Looks awesome.

> This is actually a Nuxt feature; any file with an underscore is deemed "hidden".
>
> Can I find this in the Nuxt documentation for you now? Of course I can't! 😆

Thanks. That's interesting. I'm not super familiar with Nuxt yet, but I did find something underscore related on dynamic routes in the Nuxt 2 documentation: https://v2.nuxt.com/docs/features/file-system-routing/#dynamic-routes It seems like in Nuxt 3 this works differently though.

I don't rely on underscores in filenames, so it's not an issue for me anymore.

**Comment by davestewart** [comment]
Yeah, Nuxt 3 uses `[id]` whereas Nuxt 2 used `_id` :)
