### ISSUE TITLE
contentExtensions configuration not working properly

### ISSUE THREAD

**Issue by ayZagen** [davestewart/nuxt-content-assets#63]
I would like to exclude mdx files from being detected as assets so I included following config as it defined in README:
```js
contentAssets: {
  contentExtensions: 'md mdx yml yaml json',
}
```

however mdx files are still being treated as asset files and they are copied in public folder. I can also see those files in log output when `debug: true` is set.

I also tried using regex like configuration like this:
```js
'mdx? ya?ml json'
```
but it didn't have any effect.

Am I missing something?

**Comment by davestewart** [comment]
Hey @ayZagen - sorry I've too busy to look at any OSS for a while 😬

Are you still having problems with this?

**Comment by davestewart** [comment]
Sorry again for the delay @ayZagen.

I'm working on Nuxt Content Assets right now.

Can I ask – if you're still using this package – did you load Nuxt Content Assets before Nuxt Content as per the docs?

```js
export default defineNuxtConfig({
  modules: [
    'nuxt-content-assets', // make sure to add before content!
    '@nuxt/content',
  ]
})
```

If not, let me know and I'll attempt to debug this.

**Comment by ayZagen** [comment]
Yes, I strictly followed readme. I believe this [function](https://github.com/davestewart/nuxt-content-assets/blob/55161f0e1b951a7ba0bfed3f6c30ea941ea8cc3c/src/runtime/utils/path.ts#L48) should be aware of `contentExtensions` config.

**Comment by davestewart** [comment]
Thanks for coming back to me. 

Let me take a look this afternoon and let you know.

**Comment by davestewart** [comment]
Just to keep you updated, @ayZagen...

Struggling with getting #76 over the line with some weird side effects to `nuxi prepare`.

Severely limited on time this week, but this issue is next in line.

At least I'm reacquainted with the code, and fairly sure I know what I'm looking for and where to look for it.

**Comment by davestewart** [comment]
Picked this up again today.

>  i think contentExtensions configuration has no effect at all.

So you're right – and there is a bug – but actually this is not what the job of `contentExtensions` is for.

I'm solving this in two ways:

1. preventing any recognised content file types (`md mdx csv yml yaml json`) from being copied
2. clarifying the documentation around `contentExtensions`
3. additionally, adding an example to the playground

Thanks for bringing this to my attention; I'll get this committed and pushed tonight!

**Comment by ayZagen** [comment]
Thanks a lot for your effort. I will try it as soon as possible.

**Comment by davestewart** [comment]
Sorry it took so f---ing long 😆
