### ISSUE TITLE
Cannot start nuxt if content watch is disabled

### ISSUE THREAD

**Issue by raphi-0901** [davestewart/nuxt-content-assets#72]
## Description

I get this error If the watch option of the content module is disabled:
![image](https://github.com/davestewart/nuxt-content-assets/assets/81636028/e68aee6d-6c1a-447d-a5bf-cd57cec9b6d3)

To reproduce:

- disable watch option in for content in nuxt.config.ts
```
content: {
    watch: false,
},
```

Expected result:

- start nuxt successfully even if watch is disabled

## Environment info

Run the code below and replace with the output:

```
Node v18.19.0

nuxt-app@2.4.7 /nuxt
+-- @nuxt/content@2.12.1
+-- nuxt-content-assets@1.3.7
`-- nuxt@3.11.2
```

**Comment by davestewart** [comment]
Hey, thanks for the report.

It looks like maybe the fixes that were just released may have caused this.

In the meantime you can lock your version to `1.3.3` and I'll take a look
