### ISSUE TITLE
File scanner does not work with Content v2.13+ (Nuxt 4 directory structure)

### ISSUE THREAD

**Issue by JakeIsMeh** [davestewart/nuxt-content-assets#85]
## Description
When putting `/content` in `<rootDir>`, no content is picked up due to the module still expecting it to be in `<srcDir>`

## Context
Nuxt Content 2.13 moves the `/content` directory from `<srcDir>` to `<rootDir>` in preparation for the Nuxt 4 directory structure.

https://github.com/davestewart/nuxt-content-assets/blob/d03045460c0def23a40e21df2a73c2399ae30cdc/src/module.ts#L110

## Environment info
```
Node v22.6.0

@nuxt/content 2.13.2
nuxt 3.12.4
nuxt-content-assets 1.4.4
```

**Comment by vacijj** [comment]
@davestewart [v1.5.0](https://github.com/davestewart/nuxt-content-assets/releases/tag/v1.5.0) seems not to be published on https://www.npmjs.com/package/nuxt-content-assets. Therefore the fix is not available.
