### ISSUE TITLE
_dir.yml copied but not processed

### ISSUE THREAD

**Issue by mathieunicolas** [davestewart/nuxt-content-assets#9]
### Describe the bug
Files `_dir.yml` in the content (sub)folders or fetched through the content external sources option are indeed copied in the `dist` folder, but their informations are not processed.

I tried with 2 properties : 
```yml
title: 'test content assets'
aside:
  collapsed: true
```
If i disable the `'nuxt-content-assets'` module in `nuxt.content.ts`, the file is processed, but if I enable it again the file is not processed anymore. By processed, I mean the title is not modified and the folder in DocsAsideTree is not collapsed.
My setup is very minimalist and I only use Docus and nuxt-content-assets : 

```ts
export default defineNuxtConfig({
  extends: '@nuxt-themes/docus',
  modules: [
    'nuxt-content-assets', // make sure to add before content!
    '@nuxt/content'
  ],
  css: ['@/assets/main.css'],
  content: {
    // sources: {
    //   gh: {
    //     driver: 'github',
    //     repo: 'mathieunicolas/alloe',
    //     dir: '/',
    //     prefix: '/'
    //   }
    // },
    navigation: {
      fields: ['auteur']
    }
  },
})
```
I checked in the `dist` folder and _dir.yml is actually copied, but it looks like it's not processed.

### To Reproduce
Create a `_dir.yml` file in a Docus project with `nuxt-content-assets`

### Software versions:

```
Node v18.15.0

docus-starter@0.1.0 /Users/mathieu/WebstormProjects/alloe-site
├── nuxt-content-assets@0.9.0-alpha
└── nuxt@3.3.3
```

**Comment by davestewart** [comment]
As a quick test, can you try changing the extension to `yaml`?

If that fixes it, then the change is a one-character fix!

**Comment by mathieunicolas** [comment]
Yep, good news, it works with the `*.yaml` extension !

**Comment by davestewart** [comment]
OK, just a configuration tweak and that'll be done.

Thanks for testing 🙏

**Comment by mathieunicolas** [comment]
You're the best !

**Comment by davestewart** [comment]
I try!

**Comment by davestewart** [comment]
OK, version 0.9.0-beta is on NPM now:

https://www.npmjs.com/package/nuxt-content-assets

Can you try that?

**Comment by mathieunicolas** [comment]
Amazing, it works !

**Comment by davestewart** [comment]
Awesome!

**Comment by mathieunicolas** [comment]
Thanks a lot for your time =)
